<?php /*
SQL INSERT
-----------------------

INSERT INTO TABLE_NAME (COL_NAME, COL_NAME_2, COL_NAME_3) 
VALUES 
('$VERIABLE_NAME', '$VERIABLE_EMAIL', '$VERIABLE_ADDRESS'),
('$VERIABLE_NAME_2', '$VERIABLE_EMAIL_2', '$VERIABLE_ADDRESS_2'),
('$VERIABLE_NAME_3', '$VERIABLE_EMAIL_3', '$VERIABLE_ADDRESS_3'),


2. YÖNTEM : 
INSERT INTO TABLE_NAME SET STUN_NAME = '$VERİABLE', STUN_NAME2 = '$VERİABLE'



SQL SELECT
-----------------------
SELECT * FROM TABLE_NAME 
SELECT TABLE_NAME AS TABLE FROM -> AS İFADESİ TABLE_NAME'E YENİ BİR İSİM ATAR TABLE DİYE


SQL UPDATE
-----------------------
UPDATE TABLE_NAME SET STUN_NAME = '$VERİABLE', STUN_NAME2 = '$VERİABLE' WHERE ID = '$IDS'


SQL DELETE
-----------------------
DELET FROM TABLE_NAME WHERE ID='$VERIABLE'